version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.4
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.17.4
    container_name: kibana
    depends_on:
      -  elasticsearch
    environment:
      - elasticsearch.hosts=http://localhost:9200
    ports:
      - 5601:5601
